spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: chat
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_URI}:${MONGO_DB_PORT}/${MONGO_DB_NAME}
      auto-index-creation: true
